### ISSUE TITLE
Composer instalation failing

### ISSUE THREAD

**Issue by holantomas** [Kdyby/Doctrine#305] opened 2017-09-26 08:38 UTC
Hi,
I creating new project. Wanna install kdyby/doctrine but it's failing on nette/robot-loader

PHP 7.1.9

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove nette/robot-loader v3.0.2
    - Conclusion: don't install nette/robot-loader v3.0.2
    - kdyby/doctrine v3.2.0 requires nette/robot-loader ^2.4@dev -> satisfiable by nette/robot-loader[v2.4.0, v2.4.1, v2.4.2, v2.4.3].
    - kdyby/doctrine v3.2.1 requires nette/robot-loader ^2.4@dev -> satisfiable by nette/robot-loader[v2.4.0, v2.4.1, v2.4.2, v2.4.3].
    - Can only install one of: nette/robot-loader[v2.4.0, v3.0.2].
    - Can only install one of: nette/robot-loader[v2.4.1, v3.0.2].
    - Can only install one of: nette/robot-loader[v2.4.2, v3.0.2].
    - Can only install one of: nette/robot-loader[v2.4.3, v3.0.2].
    - Installation request for nette/robot-loader (locked at v3.0.2, required as ^2.4 || ^3.0) -> satisfiable by nette/robot-loader[v3.0.2].
    - Installation request for kdyby/doctrine ^3.2 -> satisfiable by kdyby/doctrine[v3.2.0, v3.2.1].


Installation failed, reverting ./composer.json to its original content.
```

`composer info`
```
dg/adminer-custom       v1.9.2  Customization for Adminer, the best database management tool written in PHP.
holabs/authenticator    0.1     Google's Authenticator implementation for Nette framework
kdyby/events            v3.1.0  Events for Nette Framework
latte/latte             v2.4.6  ☕ Latte: the intuitive and fast template engine for those who want the most secure PHP sites. Introduces context-sensitive escaping.
nette/application       v2.4.9  🏆 Nette Application: a full-stack component-based MVC kernel for PHP that helps you write powerful and modern web applications. Write less, have cleaner code and your work w...
nette/bootstrap         v2.4.5  🅱 Nette Bootstrap: the simple way to configure and bootstrap your Nette application.
nette/caching           v2.5.6  ⏱ Nette Caching: library with easy-to-use API and many cache backends.
nette/component-model   v2.3.1  Nette Component Model
nette/database          v2.4.4  💾 Nette Database: layer with a familiar PDO-like API but much more powerful. Building queries, advanced joins, drivers for MySQL, PostgreSQL, SQLite, MS SQL Server and Oracle.
nette/di                v2.4.10 💎 Nette Dependency Injection Container: Flexible, compiled and full-featured DIC with perfectly usable autowiring and support for all new PHP 7.1 features.
nette/finder            v2.4.1  Nette Finder: Files Searching
nette/forms             v2.4.6  ?? Nette Forms: generating, validating and processing secure forms in PHP. Handy API, fully customizable, server & client side validation and mature design.
nette/http              v2.4.7  🌐 Nette Http: abstraction for HTTP request, response and session. Provides careful data sanitization and utility for URL and cookies manipulation.
nette/mail              v2.4.3  Nette Mail: Sending E-mails
nette/neon              v2.4.2  Nette NEON: parser & generator for Nette Object Notation
nette/php-generator     v2.6.3  Nette PHP Generator
nette/reflection        v2.4.2  Nette Reflection: docblock annotations parser and common reflection classes
nette/robot-loader      v3.0.2  🍀 Nette RobotLoader: high performance and comfortable autoloader that will search and autoload classes within your application.
nette/safe-stream       v2.3.3  Nette SafeStream: atomic and safe manipulation with files via native PHP functions.
nette/security          v2.4.2  Nette Security: Access Control Component
nette/tester            v2.0.0  Nette Tester: enjoyable unit testing in PHP with code coverage reporter. 🍏🍏🍎🍏
nette/utils             v2.4.8  🛠 Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, validation, slug or strong password generating etc.
paragonie/random_compat v2.0.10 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
robthree/twofactorauth  1.6     Two Factor Authentication
symfony/inflector       v3.3.9  Symfony Inflector Component
symfony/polyfill-php70  v1.5.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/property-access v3.3.9  Symfony PropertyAccess Component
tracy/tracy             v2.4.9  😎 Tracy: the addictive tool to ease debugging PHP code for cool developers. Friendly design, logging, profiler, advanced features like debugging AJAX calls or CLI support. Y...
ublaboo/datagrid        v5.4.5  DataGrid for Nette Framework: filtering, sorting, pagination, tree view, table view, translator, etc
ublaboo/responses       v1.0.6  Additional responses for Nette Framework
```

**Comment by janatjak** [comment] 2017-09-26 10:01
kdyby/doctrine is not compatible with robot/loader ^3.0 for now - #304

**Comment by enumag** [comment] 2017-12-03 10:46
Closing as duplicate of #304.

**Closed by enumag** 2017-12-03 10:46 UTC
