### ISSUE TITLE
v3.1.2 => v3.2.0 - Warning Illegal string offset 'metadata'

### ISSUE THREAD

**Issue by petrparolek** [Kdyby/Doctrine#299] opened 2017-05-27 16:24 UTC
Po update extension mě přestane fungugovat celá doctrine.
[exception--2017-05-27--16-20--a7b3c72e8c.zip](https://github.com/Kdyby/Doctrine/files/1033656/exception--2017-05-27--16-20--a7b3c72e8c.zip)

Mám nejnovější Nette 2.4.

Díky moc za pomoc.

**Comment by hubipe** [comment] 2017-05-27 16:57
Same thing here, but update version is from 3.1.2 to 3.1.3.

**Comment by hubipe** [comment] 2017-05-27 17:04
Same problem here after upgrading from 3.1.2 to 3.1.3. There are two logs in zip, one is warning from localhost, exception is from our staging server.
[exceptions.zip](https://github.com/Kdyby/Doctrine/files/1033675/exceptions.zip)

**Comment by fprochazka** [comment] 2017-05-27 17:37
I know where is the problem. Fixing it right now.

**Comment by fprochazka** [comment] 2017-05-27 17:54
@hubipe @petrparolek it should be fixed for both Nette 2.3 and 2.4, can you please confirm it? I'll release patch versions right away.

**Comment by hubipe** [comment] 2017-05-27 18:07
Yes, after installing dev-master 530662e1cc0769736d095578fb9aede502f65e86, problem is gone. Thank you

**Comment by fprochazka** [comment] 2017-05-27 18:08
That is not `dev-master` and you should not install `dev-master` right now, that would probably break your app horribly. But thanks for confirming, I'll push the tag now.

**Comment by fprochazka** [comment] 2017-05-27 18:08
Thanks for reporting!

**Closed by fprochazka** 2017-05-27 18:08 UTC

**Comment by hubipe** [comment] 2017-05-27 18:10
@fprochazka I know, I just wanted to test, if the problem is gone, and this was the easiest. I'm not gonna use dev master on production

**Comment by fprochazka** [comment] 2017-05-27 18:12
@hubipe you've linked branch `v3.2` which is perfectly correct - you didn't install master. I just wanted to point it out for people reading this issue, so they wouldn't install master.

Thanks again!

**Comment by fprochazka** [comment] 2017-05-27 18:12
The patch version is released.

**Comment by petrparolek** [comment] 2017-05-27 18:16
thanks for fixing. It's working OK
